import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { AuthContextProvider } from "@/context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" ">
      <AuthContextProvider>
        <body className="{inter.className} c">
          <nav>
            <NavBar />
          </nav>
          <div className="min-h-screen  mx-auto">{children}</div>
        </body>
      </AuthContextProvider>
    </html>
  );
}
